

# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [20]:
import numpy as np


#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [32]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [33]:
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [34]:
b=np.arange(10,49)

In [35]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [38]:
c=np.random.randint(0,8,(3,3))
c


array([[5, 1, 2],
       [1, 6, 6],
       [2, 7, 4]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [39]:
t=[1,2,0,0,4,0]
d=np.nonzero(t)
d

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [40]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [41]:
e=np.random.random((3,3,3))
e

array([[[0.50269316, 0.17874146, 0.89137487],
        [0.32354282, 0.4436779 , 0.12050803],
        [0.65411684, 0.47767265, 0.75874473]],

       [[0.31485868, 0.70692698, 0.10487591],
        [0.28225005, 0.57715385, 0.38191554],
        [0.03895546, 0.32105864, 0.28689749]],

       [[0.16151296, 0.50788083, 0.70255015],
        [0.03491315, 0.11648126, 0.46404016],
        [0.99287767, 0.82372449, 0.26146367]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [49]:
f=np.random.random((10,10))
f



array([[0.67353224, 0.66923933, 0.29611773, 0.66772548, 0.53960564,
        0.2673939 , 0.66553081, 0.16646913, 0.78147546, 0.33188655],
       [0.90356128, 0.00377042, 0.79284141, 0.61570579, 0.89359792,
        0.42092298, 0.44725143, 0.68193059, 0.6085432 , 0.92523739],
       [0.82505607, 0.86160178, 0.82074755, 0.58674638, 0.61726298,
        0.50711282, 0.61014735, 0.45502229, 0.13400505, 0.14272386],
       [0.18941397, 0.76122033, 0.04327981, 0.36224689, 0.14123269,
        0.757912  , 0.75944782, 0.67183579, 0.61166477, 0.77749857],
       [0.16412924, 0.77953805, 0.91066506, 0.70202806, 0.73654086,
        0.15643725, 0.24468672, 0.84542982, 0.33952465, 0.05691232],
       [0.82850375, 0.69363524, 0.68654031, 0.24949207, 0.64283415,
        0.1658955 , 0.78941092, 0.06233148, 0.42627002, 0.65357021],
       [0.52747281, 0.94827421, 0.71957904, 0.30274899, 0.04379394,
        0.33534919, 0.35720797, 0.27975598, 0.28131818, 0.14225065],
       [0.82251987, 0.95504583, 0.7467508

In [50]:
g=np.max(f)
g

0.9832086493380789

In [51]:

h=np.min(f)
h

0.003770424781780357

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag

In [80]:
k=np.arange(25).reshape((5,5))

r=[1,2,3,4]
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
np.diag(np.diag((k)))

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

In [76]:
matrix = np.zeros((4, 4), float)
main = np.array([2,2,2,2])
np.fill_diagonal(matrix, main)
matrix

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [81]:
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
np.fill_diagonal(k[1:,:-1],r)

In [83]:
k

array([[ 0,  1,  2,  3,  4],
       [ 1,  6,  7,  8,  9],
       [10,  2, 12, 13, 14],
       [15, 16,  3, 18, 19],
       [20, 21, 22,  4, 24]])

In [86]:
k[1:,:-1]

array([[ 1,  6,  7,  8],
       [10,  2, 12, 13],
       [15, 16,  3, 18],
       [20, 21, 22,  4]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [89]:
#to scale the values such that that the range of the 
#row or column values is between 0 and 1. 

j=np.random.random((5,5))
j


array([[0.35949814, 0.72599943, 0.7382241 , 0.66606365, 0.38859441],
       [0.05709729, 0.07298935, 0.966156  , 0.02192714, 0.85350204],
       [0.63360053, 0.67429138, 0.08739486, 0.02331084, 0.94436106],
       [0.0809801 , 0.23069241, 0.93001439, 0.03395867, 0.65174683],
       [0.39528652, 0.62146804, 0.29111418, 0.201274  , 0.33297886]])

In [90]:
mean=np.mean(j)

In [91]:
std=np.std(j)

In [97]:
j

array([[0.35949814, 0.72599943, 0.7382241 , 0.66606365, 0.38859441],
       [0.05709729, 0.07298935, 0.966156  , 0.02192714, 0.85350204],
       [0.63360053, 0.67429138, 0.08739486, 0.02331084, 0.94436106],
       [0.0809801 , 0.23069241, 0.93001439, 0.03395867, 0.65174683],
       [0.39528652, 0.62146804, 0.29111418, 0.201274  , 0.33297886]])

In [98]:
l=(j-mean)/std

In [93]:
print(l)

[[-0.25097469  0.9016479   0.94009368  0.71315379 -0.1594688 ]
 [-1.20200558 -1.15202608  1.65692461 -1.31261338  1.30263528]
 [ 0.6110594   0.73902948 -1.10672168 -1.30826174  1.58838094]
 [-1.1268957  -0.65606027  1.54326161 -1.27477501  0.66812834]
 [-0.13842256  0.57290353 -0.46603775 -0.74857926 -0.33437606]]


In [95]:
hej=l[0,0]+l[0,1]+l[0,2]+l[0,3]+l[0,4]
print (hej)

2.1444518837839888


In [96]:
from sklearn.preprocessing import normalize


In [99]:
normalized=normalize(j,axis=1,norm="l1")

In [100]:
normalized

array([[0.12489601, 0.25222504, 0.2564721 , 0.23140229, 0.13500457],
       [0.02895882, 0.03701901, 0.49001867, 0.01112109, 0.43288241],
       [0.26813864, 0.28535894, 0.03698535, 0.00986511, 0.39965196],
       [0.04201537, 0.11969146, 0.48252467, 0.01761897, 0.33814953],
       [0.21458221, 0.33736537, 0.15803201, 0.10926206, 0.18075835]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [101]:
a=[[1,2,3],[2,3,4],[1,0,4]]
b=[[1,3,4],[2,0,0],[0,0,3]]

B=np.array(b)
B

array([[1, 3, 4],
       [2, 0, 0],
       [0, 0, 3]])

In [103]:
A=np.array(a)
A


array([[1, 2, 3],
       [2, 3, 4],
       [1, 0, 4]])

In [104]:
np.intersect1d(A,B)

array([0, 1, 2, 3, 4])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`


In [111]:
z=np.random.rand(10)
z

array([0.78759113, 0.41300697, 0.80283016, 0.88071863, 0.86877414,
       0.4961772 , 0.12947015, 0.6773096 , 0.14224844, 0.1520986 ])

In [112]:
print(np.sort(z))


[0.12947015 0.14224844 0.1520986  0.41300697 0.4961772  0.6773096
 0.78759113 0.80283016 0.86877414 0.88071863]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax

In [113]:
zz=np.random.rand(10)
zz

array([0.19385352, 0.15653661, 0.46657161, 0.56592248, 0.24436096,
       0.67035788, 0.86363553, 0.71343716, 0.56983353, 0.97245593])

In [114]:
np.argmax(zz)

9

In [115]:
zz[9]=0
zz

array([0.19385352, 0.15653661, 0.46657161, 0.56592248, 0.24436096,
       0.67035788, 0.86363553, 0.71343716, 0.56983353, 0.        ])

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [129]:
cc=np.random.randint(0,4,(3,3))
cc

array([[1, 0, 2],
       [0, 3, 0],
       [0, 2, 3]])

In [134]:
np.mean(cc,0)

array([0.33333333, 1.66666667, 1.66666667])

In [146]:
# I have no idea what subtract means here??


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000) 
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition

In [153]:
z=np.arange(10000)
np.random.shuffle(z)
z

array([3033, 1997, 2588, ...,  248, 8170, 1888])

In [155]:
a=np.argmax(z)
a

5988

In [156]:
z[5988]

9999

In [157]:
b=np.argsort(z)

b

array([3985, 1749, 5713, ..., 9891,  820, 5988])

In [158]:
b[-5]

9954

In [159]:
z[9954]

9995

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [192]:
w=np.random.randint(0,10,(5,3))
w

array([[9, 5, 8],
       [9, 7, 0],
       [1, 4, 3],
       [7, 1, 5],
       [9, 9, 7]])

In [195]:
l= np.where(w==4)

l

(array([2]), array([1]))

In [196]:
w

array([[9, 5, 8],
       [9, 7, 0],
       [1, 4, 3],
       [7, 1, 5],
       [9, 9, 7]])

In [197]:
w[2,1]=((w[2,1])**2)
w


array([[ 9,  5,  8],
       [ 9,  7,  0],
       [ 1, 16,  3],
       [ 7,  1,  5],
       [ 9,  9,  7]])